[sdl]
fullscreen = false
window_size = 1280x960
output = opengl

[render]
aspect = true
shader = sharp

[cpu]
core = auto
cputype = auto
cpu_cycles = 20000

[mixer]
rate = 44100
blocksize = 1024
prebuffer = 25

[sblaster]
sbtype = sb16
sbbase = 220
irq = 7
dma = 1
hdma = 5
sbmixer = true

[gus]
gus = true
gusbase = 240
gusirq = 5
gusdma = 3

[autoexec]
@echo off
mount c "res\minebomb"
c:
cls
echo ========================================================
echo   MINE BOMBERS 3.11 (1995) - Skitso Productions
echo ========================================================
echo.
echo   [ SPEED CONTROLS IN GAME ]
echo   - Ctrl + F11   : Slow Down
echo   - Ctrl + F12   : Speed Up
echo   - Alt  + F12   : Turbo Fast-Forward Mode
echo   - Alt  + Enter : Fullscreen Toggle
echo.
echo ========================================================
echo Starting MB.EXE...
MB.EXE
exit
